name: Triggered Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled

on:
  repository_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event
        run: echo "This is a triggered event."
