name: Triggered Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled

on:
  repository_dispatch:
    inputs:
      message:
        default: production


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event
        run: echo "This is a triggered event. ${{github.event.inputs.message}} -  {{ inputs.message }}"
